In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['embarked']=lb.fit_transform(df['embarked'])

In [6]:
df['embarked'].unique()

array([2, 0, 1, 3])

In [7]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [9]:
df['sex']=lb.fit_transform(df['sex'])

In [10]:
df['sex'].unique()

array([1, 0])

In [11]:
df['sex']=lb.fit_transform(df['class'])

In [12]:
df['sex'].unique()

array([2, 0, 1])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    int64   
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     891 non-null    int64   
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(6), object(3)
memory usage: 80.7+ KB


In [14]:
pd.get_dummies(df,columns=['embark_town'],drop_first=True)

survived  pclass  sex   age  sibsp  parch     fare  embarked   class  \
0           0       3    2  22.0      1      0   7.2500         2   Third   
1           1       1    0  38.0      1      0  71.2833         0   First   
2           1       3    2  26.0      0      0   7.9250         2   Third   
3           1       1    0  35.0      1      0  53.1000         2   First   
4           0       3    2  35.0      0      0   8.0500         2   Third   
..        ...     ...  ...   ...    ...    ...      ...       ...     ...   
886         0       2    1  27.0      0      0  13.0000         2  Second   
887         1       1    0  19.0      0      0  30.0000         2   First   
888         0       3    2   NaN      1      2  23.4500         2   Third   
889         1       1    0  26.0      0      0  30.0000         0   First   
890         0       3    2  32.0      0      0   7.7500         1   Third   

       who  adult_male deck alive  alone  embark_town_Queenstown  \
0      man        True  NaN    no  False                   False   
1    woman       False    C   yes  False                   False   
2    woman       False  NaN   yes   True                   False   
3    woman       False    C   yes  False                   False   
4      man        True  NaN    no   True                   False   
..     ...         ...  ...   ...    ...                     ...   
886    man        True  NaN    no   True                   False   
887  woman       False    B   yes   True                   False   
888  woman       False  NaN    no  False                   False   
889    man        True    C   yes   True                   False   
890    man        True  NaN    no   True                    True   

     embark_town_Southampton  
0                       True  
1                      False  
2                       True  
3                       True  
4                       True  
..                       ...  
886                     True  
887                     True  
888                     True  
889                    False  
890                    False  

[891 rows x 16 columns]